# Site settings
title: Git2Go - The Git client for iOS you always wanted
email: git2go@nerdishbynature.com
description: > # this means to ignore newlines until "baseurl:"
  Git2Go finally gives you all the git functionalities you always wanted on your iOS device. Connect GitHub accounts, push commits.
baseurl: "/git2go-com/" # the subpath of your site, e.g. /blog/
url: "http://nerdishbynature.com" # the base hostname & protocol for your site
twitter_username: Git2Go
github_username:  nerdishbynature

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
